### ISSUE TITLE
Using glob fails permissions on folders 

### ISSUE THREAD

**Issue by BradTotaro** [MakerDepotAcademy/quizshow#1]
brad@PotatoCannon:~/mda/quizshow$ python QuizShowGamePlay.py 
Traceback (most recent call last):
  File "QuizShowGamePlay.py", line 12, in <module>
    Boards = Manager()
  File "/home/brad/mda/quizshow/gpio32/lib.py", line 81, in __init__
    for acm in Path('/dev').glob('**/ttyACM*'):
  File "/home/brad/.local/lib/python2.7/site-packages/pathlib.py", line 997, in glob
    for p in selector.select_from(self):
  File "/home/brad/.local/lib/python2.7/site-packages/pathlib.py", line 525, in _select_from
    for p in successor_select(starting_point, is_dir, exists, listdir):
  File "/home/brad/.local/lib/python2.7/site-packages/pathlib.py", line 496, in _select_from
    for name in listdir(parent_path):
  File "/home/brad/.local/lib/python2.7/site-packages/pathlib.py", line 419, in wrapper
    value = cache[args] = func(*args)
  File "/home/brad/.local/lib/python2.7/site-packages/pathlib.py", line 346, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 13] Permission denied: '/dev/vboxusb'

**Comment by BradTotaro** [comment]
https://github.com/MakerDepotAcademy/quizshow/commit/b4c07aabcfe2fe2c588349d2c383e10b827a56ab
fixes
